Repository team-yuml-kkks/DecentWorkWeb, pull requests merged in 2019-01, with the labels that each got.

#96 Feature/add notice
  decentwork/apps/cities/urls.py
  decentwork/apps/cities/views.py
  decentwork/apps/professions/urls.py
  decentwork/apps/professions/views.py
  decentwork/assets/app.js
  decentwork/assets/components/addNotice.vue
  decentwork/assets/components/cities.vue
  decentwork/assets/components/professions.vue
  decentwork/assets/scss/main.scss
  decentwork/assets/store.js
Labels: enhancement

#104 Add notice details
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/components/noticeList.vue
  decentwork/assets/router.js
  decentwork/assets/scss/main.scss
Labels: enhancement

#106 Add profileDetails
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/components/profileDetails.vue
  decentwork/assets/components/workerList.vue
  decentwork/assets/router.js
Labels: enhancement

#108 Fix notices app tests
  decentwork/apps/notices/tests.py
Labels: bug, refactor, tests

#107 Add assignment buttons
  decentwork/assets/components/noticeDetails.vue
Labels: enhancement

#110 Feature/style
  decentwork/assets/components/addNotice.vue
  decentwork/assets/components/changePassword.vue
  decentwork/assets/components/cities.vue
  decentwork/assets/components/editProfile.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/components/noticeList.vue
  decentwork/assets/components/professions.vue
  decentwork/assets/components/profileDetails.vue
  decentwork/assets/components/workerList.vue
  decentwork/assets/scss/main.scss
  decentwork/templates/account/login.html
  decentwork/templates/account/password_reset.html
  decentwork/templates/account/signup.html
Labels: enhancement, refactor

#112 Add history mode
  decentwork/apps/home/urls.py
  decentwork/apps/home/views.py
  decentwork/assets/components/noticeList.vue
  decentwork/assets/router.js
  decentwork/urls.py
Labels: enhancement

#118 Add edit notice
  decentwork/assets/components/cities.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/components/professions.vue
Labels: enhancement

#119 Join professions with comma
  decentwork/assets/components/workerList.vue
Labels: bug

#120 Add class to pagination buttons
  decentwork/assets/components/noticeList.vue
Labels: bug

#121 Add style to autocomplite profession and city
  decentwork/assets/scss/main.scss
Labels: refactor

#122 Add posibility to close notice
  decentwork/assets/components/noticeDetails.vue
Labels: enhancement

#124 Improvement/overall improvements
  decentwork/assets/components/addNotice.vue
  decentwork/assets/components/changePassword.vue
  decentwork/assets/components/editProfile.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/components/noticeList.vue
  decentwork/assets/components/profileDetails.vue
  decentwork/assets/store.js
Labels: refactor

#126 Hide some features when user is not logged in
  decentwork/apps/home/views.py
  decentwork/assets/components/navbar.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/templates/home.html
Labels: enhancement

#127 Add description to home and fix title in notice details
  decentwork/assets/components/home.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/scss/main.scss
  decentwork/settings/base.py
Labels: bug, refactor

#125 Add rating
  decentwork/apps/profiles/admin.py
  decentwork/apps/profiles/migrations/0004_auto_20190108_1906.py
  decentwork/apps/profiles/migrations/0005_auto_20190108_1930.py
  decentwork/apps/profiles/migrations/0006_auto_20190109_0832.py
  decentwork/apps/profiles/models.py
  decentwork/apps/profiles/serializers.py
  decentwork/apps/profiles/tests.py
  decentwork/apps/profiles/views.py
Labels: enhancement

#130 Fix login
  decentwork/apps/common/views.py
Labels: bug

#132 Fix 3 main views
  decentwork/apps/home/views.py
  decentwork/assets/components/editProfile.vue
  decentwork/assets/components/noticeDetails.vue
  decentwork/assets/store.js
Labels: bug
